adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),
    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_update'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),
    path('products/create/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

authapp/urls.py
import authapp.views as authapp
from django.urls import re_path

app_name = 'authapp'


urlpatterns = [
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
    ]

geekshop/urls.py
import mainapp.views as mainapp
import authapp.views as authapp
import basketapp.views as basketapp
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('product/<int:pk>', mainapp.product, name='product'),
    path('catalog/', mainapp.catalog, name='catalog'),
    path('products/', mainapp.products, name='products'),
    path('products/page/<int:page>/', mainapp.products, name='page'),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('strollers/', mainapp.strollers, name='strollers'),
    path('chears/', mainapp.chears, name='chears'),
    path('carseats/', mainapp.carseats, name='carseats'),
    path('black_grey/', mainapp.black_grey, name='black_grey'),
    path('black_red/', mainapp.black_red, name='black_red'),
    path('black_stars/', mainapp.black_stars, name='black_stars'),
    path('admin/', admin.site.urls),
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('basket/', basketapp.basket, name='basket'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('basket/edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
    path('myadmin/', include('adminapp.urls', namespace='myadmin')),
    path('auth', include('authapp.urls', namespace='auth')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),
]
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm
from mainapp.models import ProductCategory
from mainapp.models import Product

class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect
from mainapp.models import Product, ProductCategory
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse, reverse_lazy
from adminapp.forms import ShopUserAdminEditForm, ProductCategoryEditForm, ProductEditForm
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.db import connection

class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'список пользователей'
        return context

class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin:categories')
    form_class = ProductCategoryEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/создание'
        return context

def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]

@receiver(pre_save, sender=ProductCategory)
def product_is_active_update_productcategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.product_set.update(is_active=True)
        else:
            instance.product_set.update(is_active=False)

        db_profile_by_type(sender, 'UPDATE', connection.queries)
    
#class ProductCategoryUpdateView(UpdateView):
#     model = ProductCategory
#    template_name = 'adminapp/category_update.html'
#    success_url = reverse_lazy('admin:categories')
#    form_class = ProductCategoryEditForm
#
#    def get_context_data(self, **kwargs):
#        context = super().get_context_data(**kwargs)
#        context['title'] = 'категории/редактирование'
#        return context

#class ProductCategoryDeleteView(DeleteView):
#    model = ProductCategory
#    template_name = 'adminapp/category_delete.html'
#    success_url = reverse_lazy('admin:categories')
#
#    def delete(self, request, *args, **kwargs):
#        self.object = self.get_object()
#        self.object.is_active = False
#        self.object.save()
#        return HttpResponseRedirect(self.get_success_url())
#
#    def get_context_data(self, **kwargs):
#        context = super().get_context_data(**kwargs)
#        context['title'] = 'категории/удаление'
#        return context

class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'

    #@user_passes_test(lambda u: u.is_superuser)
#def users(request):
#    title = 'админка/пользователи'
#    users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
#    context = {
#        'title': title,
#        'objects': users_list,
#    }
#    return render(request, 'adminapp/users.html', context)


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    title = 'пользователи/создание'
    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('myadmin:users'))
    else:
        user_form = ShopUserRegisterForm()
    context = {'title': title,
               'update_form': user_form,
               }
    return render(request, 'adminapp/user_update.html', context)

@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    title = 'пользователи/редактирование'
    edit_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        edit_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('myadmin:user_update', args=[edit_user.pk]))
    else:
        edit_form = ShopUserAdminEditForm(instance=edit_user)
    context = {'title': title,
               'update_form': edit_form,
               }
    return render(request, 'adminapp/user_update.html', context)

@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    title = 'пользователи/удаление'

    user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        # user.delete()
        # вместо удаления лучше сделаем неактивным
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('myadmin:users'))

    context = {'title': title,
               'user_to_delete': user,
               }

    return render(request, 'adminapp/user_delete.html', context)

@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = 'админка/категории'
    categories_list = ProductCategory.objects.all()
    context = {
        'title': title,
        'objects': categories_list,
    }
    return render(request, 'adminapp/categories.html', context)

# @user_passes_test(lambda u: u.is_superuser)
# def category_create(request):
#     title = 'категории/создание'
#
#     if request.method == 'POST':
#         category_form = ProductCategoryEditForm(request.POST, request.FILES)
#         if category_form.is_valid():
#             category_form.save()
#             return HttpResponseRedirect(reverse('myadmin:categories'))
#     else:
#         category_form = ProductCategoryEditForm()
#
#     context = {'title': title,
#                'create_form': category_form,
#                }
#
#     return render(request, 'adminapp/category_create.html', context)

# @user_passes_test(lambda u: u.is_superuser)
# def category_update(request, pk):
#     title = 'категории/редактирование'
#
#     edit_category = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         edit_form = ProductCategoryEditForm(request.POST, request.FILES, instance=edit_category)
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('myadmin:category_update', args=[edit_category.pk]))
#     else:
#         edit_form = ProductCategoryEditForm(instance=edit_category)
#     context = {'title': title,
#                'update_form': edit_form,
#                }
#     return render(request, 'adminapp/category_update.html', context)

# @user_passes_test(lambda u: u.is_superuser)
# def category_delete(request, pk):
#     title = 'категории/удаление'
#     category = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         # category.delete()
#         # вместо удаления лучше сделаем неактивным
#         category.is_active = False
#         category.save()
#         return HttpResponseRedirect(reverse('myadmin:categories'))
#     context = {'title': title,
#                'category_to_delete': category,
#                }
#     return render(request, 'adminapp/category_delete.html', context)

@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)
    context = {
        'title': 'админка/продукт',
        'category': category,
        'object_list': category.product_set.all(),
    }
    return render(request, 'adminapp/products.html', context)

@user_passes_test(lambda u: u.is_superuser)
def product_create(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        form = ProductEditForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('myadmin:products', kwargs={"pk":pk}))
    else:
        form = ProductEditForm(initial={'category': category})
    context = {'title': 'продукт/создание',
               'form': form,
               'category': category,
               }
    return render(request, 'adminapp/product_update.html', context)

# @user_passes_test(lambda u: u.is_superuser)
# def product_read(request, pk):
#     title = 'продукт/подробнее'
#     product = get_object_or_404(Product, pk=pk)
#     context = {'title': title, 'object': product, }
#
#     return render(request, 'adminapp/product_read.html', context)

@user_passes_test(lambda u: u.is_superuser)
def product_update(request, pk):
    edit_product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_product)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('myadmin:product_update', args=[edit_product.pk]))
    else:
        edit_form = ProductEditForm(instance=edit_product)
    context = {'title': 'продукт/редактирование',
               'form': edit_form,
               'category': edit_product.category,
               }
    return render(request, 'adminapp/product_update.html', context)

@user_passes_test(lambda u: u.is_superuser)
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.is_active = False
        product.save()
        return HttpResponseRedirect(reverse('myadmin:products',
                                            kwargs={"pk":product.category.pk}))
    context = {'title': 'продукт/удаление',
               'object': product,
               }

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ title|title }}</title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
</head>
<body>

<div class="admin_container">
    <div class="h2 text-center head">
        Админка
    </div>
    {% block menu %}
    <div class="admin_menu">
        {% include 'adminapp/includes/inc_menu.html' %}
    </div>
    {% endblock %}

    {% block main %}
    {% endblock %}
</div>
</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block main %}
<div class="categories_list">
    <button class="new_category">
        <a href="{% url 'myadmin:category_update' %}">
            новая категория
        </a>
    </button>
    {% for object in objects %}
    <div class="category_record
        {% if not object.is_active %}
            not_active
        {% endif %}">
        <div class="category_name">
            {{ object.name|title }}
        </div>
        <div class="category_name">
            {{ object.name|title }}
        </div>
        <div class="category_actions">
            <button>
                <a href="{% url 'myadmin:products' object.pk %}">
                    товары категории
                </a>
            </button>
            <button>
                <a href="{% url 'myadmin:category_update' object.pk %}">
                    редактировать
                </a>
            </button>
            <button>
                <a href="{% url 'myadmin:category_delete' object.pk %}">
                    удалить
                </a>
            </button>
        </div>
        <div class="category_desc">
            {{ object.description|title }}
        </div>
    </div>
    {% endfor%}
</div>
{% endblock %}

adminapp/templates/adminapp/category_create.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block main %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'myadmin:categories' %}">
      к списку категорий
    </a>
  </button>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block main %}
  <div class="user_delete">
    Уверены, что хотите удалить {{ category_to_delete.name }}
    <form action="{{ object.name }}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'myadmin:categories' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block main %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'myadmin:categories' %}">
      к списку категорий
    </a>
  </button>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block main %}
  <div class="user_delete">
    Уверены, что хотите удалить {{ object.name }}
    <form method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'myadmin:products' object.category.pk %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block main %}
<div class="product_read">
    <div class="product_name">
        Продукт<strong>{{ object.category.name|title }} {{ object.name|title }}</strong>
    </div>
    <img src="/media/{{ object.image|default:'products_images/default.jpg' }}"
         alt="{{ object.name }}"
         width="200">
    <div class="summary">
        <b>цена</b>
        <p>{{ object.price }} руб</p>
        <b>количество</b>
        <p>{{ object.quantity }}</p>
        <b>в каталоге</b>
        <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
        <p>
            <button>
                <a href="{% url 'myadmin:product_update' object.pk %}">
                    редактировать
                </a>
            </button>
        </p>
        <p>
            <button>
                <a href="{% url 'myadmin:product_delete' object.pk %}">
                    удалить
                </a>
            </button>
        </p>
        <p>
            <button>
                <a href="{% url 'myadmin:products' object.category.pk %}">
                    назад
                </a>
            </button>
        </p>
    </div>
    <div class="product_desc">
        <b>краткая информация</b>
        <p>{{ object.short_desc }}</p>
        <br><br>
        <b>подробная информация</b>
        <p>{{ object.description }}</p>
    </div>
</div>
{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block main %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'myadmin:products' category.pk %}">
      к списку товаров
    </a>
  </button>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% load my_tags %}

{% block main %}
<div class="products_list">
    <button class="new_product">
        <a href="{% url 'myadmin:product_create' category.pk %}">
            новый продукт
        </a>
    </button>

    {% for object in object_list %}
    <div class="product_record">
        <img
                src="{{object.image|media_folder_products}}"
                alt="{{ object.name }}"
                width="200">
        <div class="product_name">
            {{ object.name|title }}
        </div>
        <div class="product_actions">
            <button>
                <a href="{% url 'myadmin:product_read' object.pk %}">
                    подробнее
                </a>
            </button>
            <button>
                <a href="{% url 'myadmin:product_update' object.pk %}">
                    редактировать
                </a>
            </button>
            <button>
                <a href="{% url 'myadmin:product_delete' object.pk %}">
                    удалить
                </a>
            </button>
        </div>
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
            {{ object.short_desc|title }}
        </div>
    </div>
    {% endfor%}
</div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block main %}
  <div class="user_delete">
    Уверены, что хотите удалить {{ user_to_delete.username }}
    {% if user_to_delete.first_name %}
      ({{ user_to_delete.first_name|title }}</b>
      {% if user_to_delete.last_name %}
        {{ user_to_delete.last_name|title }}
      {% endif %})
    {% endif %}
    ?
    <form action="{% url 'myadmin:user_delete' user_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'myadmin:users' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block main %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ update_form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'myadmin:users' %}">
      к списку пользователей
    </a>
  </button>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% load my_tags %}

{% block main %}
<div class="users_list">
    <button class="new_user">
        <a href="{% url 'myadmin:user_create' %}">
        новый пользователь
        </a>
    </button>
    {% for object in object_list %}
    <div
            class="user_record {% if not object.is_active %}not_active{% endif %}">
        <img
                src="{{ object.avatar|media_folder_users }}"
                alt="{{ object.username }}">
        <div class="user_role">
            {% if object.is_superuser %}
            администратор
            {% else %}
            пользователь
            {% endif %}
            <button>
                <a href="{% url 'myadmin:user_update' object.pk %}">
                редактировать
                </a>
            </button>
            <button>
                <a href="{% url 'myadmin:user_delete' object.pk %}">
                удалить
                </a>
            </button>
        </div>
        <div class="user_name">
            <p><strong>{{ object.username }}</strong></p>
            <p>
                {% if object.first_name %}
                <b>{{ object.first_name|title }}</b>
                {% if object.last_name %}
            <p>{{ object.last_name|title }}</p>
            {% endif %}
            {% endif %}
            </p>
        </div>
        <div class="user_age">
            age:<br>
            {{ object.age }} лет
        </div>
        <div class="user_email">
            email:<br>
            {{ object.email }}
        </div>
        <div class="user_lastlogin">
            logged:<br>
            {{ object.last_login }}
        </div>
    </div>
    {% endfor%}
</div>
{% endblock %}